makerules/Makefile_linux-extras

$(shell) fails to captures the output and run the commands for use in the makefile.This causes make linux to fail. So run the commands without using shell.

Remove $(shell) from linux-extras makefile

---

configs/platforms/am62xxsip-evm-rt.mk
configs/platforms/am62xxsip-evm.mk
makerules/Makefile_u-boot

Instead of creating a new variable, instead mention the fragment config with space and it will picked up by the makefile target.

Change how fragment defconfig is passed to uboot

---

configs/platforms/am62xxsip-evm-rt.mk
configs/platforms/am62xxsip-evm.mk

PVR_BUILD_DIR is same as for all am62 variants.
So update the variable value to am62_linux.

Update PVR_BUILD_DIR for am62xxsip

---

configs/platforms/am335x-evm-rt.mk
configs/platforms/am437x-evm-rt.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xxsip-evm-rt.mk
configs/platforms/am64xx-evm-rt.mk
configs/platforms/am65xx-evm-rt.mk
makerules/Makefile_linux
makerules/Makefile_linux-dtbs
makerules/Makefile_linux-extras
makerules/Makefile_linux-extras-dtbs
makerules/Makefile_linux-legacy
makerules/Makefile_linux-legacy-dtbs

make defconfig needs to include a fragment config when building a rt image. So add a new variable RT_FRAGMENT for rt makefile and also for all platforms.

Add fragment config for rt kernel

---

configs/platforms/am65xx-evm-rt.mk
configs/platforms/am65xx-evm.mk

Add TARGET_PRODUCT=ti654x in config file for am65 for rt and non rt. This is needed for ti-sgx makefile.

Add target product variable for am65

---

configs/platforms/am65xx-evm-rt.mk
configs/platforms/am65xx-evm.mk

makefile target for pdm anamoly detection has a package bug due to compiler hence removing it now for linux and rt linux.

Remove pdm anamoly detection target from am65

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk

fitimage build needs some dtb overlays which are missing when
device trees are parsed. Add the missing dtbs

am62pxx-evm: Fix fitimage build for am62p

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xx-evm.mk
makerules/Makefile_jailhouse
makerules/Makefile_linux-extras

Add sysroot path in makefile_jailhouse.
Update path for uboot-extras-jailhouse.
Update linux-extras so it picks prebuild binaries for jailhouse.

Fix jailhouse makefile for am62 and am62p

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xx-evm.mk

uboot extras repo will be packaged via yocto so use yocto core bundle name.

Change name of uboot-extras repo

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xx-evm.mk

- jailhouse, linux-extras & u-boot-extras with Kernel 6.6 & U-boot 2024.04 is still WIP.
- Hence, temporarily remove these three targets from MAKE_ALL_TARGETS for AM62x & AM62P.

configs: Temporarily remove jailhouse targets

---

configs/platforms/am62xxsip-evm-rt.mk
configs/platforms/am62xxsip-evm.mk

Update a53 and r5 defconfig names for am62xxsip based on U-Boot 2024.04 [1]
[1] https://git.ti.com/cgit/ti-u-boot/ti-u-boot/commit/?h=ti-u-boot-2024.04&id=df5181f8c6c41bf018ec043d565581b5d8a291c5

configs: platforms: Update UBOOT_MACHINE for am62xxsip

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xx-evm.mk

- Add jailhouse support back in Top Level Makefile of SDK Installer.
- This reverts commit a62f020c74799ad566e5933c3fbd23dc974229f4.

Revert "configs: Temporarily remove jailhouse targets"

---

configs/platforms/am62lxx-evm-rt.mk
configs/platforms/am62lxx-evm.mk
makerules/Makefile_linux
makerules/Makefile_u-boot

- Add platform support for AM62L Linux & RT-Linux
- Update u-boot Makefile to support AM62L. This involves passing BL1 to binman, skipping u-boot-r5 build & copying boot binaries from relevant locations.

ti-tisdk-makefile: Add support for AM62L

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xx-evm.mk
configs/platforms/am62xxsip-evm-rt.mk
configs/platforms/am62xxsip-evm.mk
makerules/Makefile_ti-img-rogue-driver

- Remove `RGX_BVNC` definition from all platform configurations.
- Skip passing `RGX_BVNC` to the makefile, as it is already defined within the makefile itself.

configs:platforms: Update makefile configs for ti-img-rogue-driver

---

makerules/Makefile_linux
makerules/Makefile_linux-extras

- U-Boot tree doesn't have any `board/ti/keys` directory containing keys to use for signing was incorrect.
- The keys are located in `arch/arm/mach-k3/keys` under U-Boot sources [1]. Hence, update the mkimage command to pass this directory.
[1]: https://git.ti.com/cgit/ti-u-boot/ti-u-boot/tree/arch/arm/mach-k3/keys?h=ti-u-boot-2024.04

makerules: Update key-directory passed to mkimage

---

configs/platforms/am335x-evm-rt.mk
configs/platforms/am335x-evm.mk
configs/platforms/am335x-hs-evm-rt.mk
configs/platforms/am335x-hs-evm.mk
configs/platforms/am437x-evm-rt.mk
configs/platforms/am437x-evm.mk
configs/platforms/am437x-hs-evm-rt.mk
configs/platforms/am437x-hs-evm.mk
configs/platforms/am65xx-evm-rt.mk
configs/platforms/am65xx-evm.mk

We don't package sources for ti-sgx-ddk-km under tisdk-core-bundle [1] Hence, drop it from MAKE_ALL_TARGETS to avoid installer build failures
[1]: https://git.ti.com/cgit/ti-sdk-linux/meta-tisdk/tree/recipes-core/packagegroups/packagegroup-arago-tisdk-sourceipks-sdk-host.bb?h=kirkstone#n25

configs: platforms: Drop ti-sgx-ddk-km from MAKE_ALL_TARGETS

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk

Overlays for interfacing OV5640 sensor with V3Link are built as part of the TI linux kernel [1]. So, add an entry for it in SDK Makefile
[1]: https://git.ti.com/cgit/arago-project/meta-ti/commit/?h=scarthgap&id=a4defea6f5bd69b6e5a5fde3b88f5f0e80d11f6b

configs: platforms: am62pxx: Pick overlays for V3Link cameras

---

configs/platforms/am62pxx-evm-rt.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm-rt.mk
configs/platforms/am62xx-evm.mk
configs/platforms/am62xxsip-evm-rt.mk
configs/platforms/am62xxsip-evm.mk
configs/platforms/am64xx-evm-rt.mk
configs/platforms/am64xx-evm.mk
configs/platforms/am65xx-evm-rt.mk
configs/platforms/am65xx-evm.mk

Update ``MKIMAGE_DTB_FILE`` path related to u-boot 2025.01 migration.
dtb files path changed from ``a53/arch/arm/dts/`` to ``a53/dts/upstream/src/arm64/ti/``

configs:platforms: Update the dtb file path in u-boot machine configs

---

makerules/Makefile_linux-extras
makerules/Makefile_u-boot-extras

Update the makefiles to add AM62L specific makerules. This commit in continuation to the 49b702e1a488427d89a6cb432c8e57fa7b6ac758 commit enables building and enabling the binaries through makefiles.

makerules: update linux-extras, u-boot-extras makefiles to build AM62L

---

configs/platforms/am335x-evm.mk
configs/platforms/am335x-hs-evm.mk
configs/platforms/am437x-evm.mk
configs/platforms/am437x-hs-evm.mk
configs/platforms/am62axx-evm.mk
configs/platforms/am62lxx-evm.mk
configs/platforms/am62pxx-evm.mk
configs/platforms/am62xx-evm.mk
configs/platforms/am62xxsip-evm.mk
configs/platforms/am64xx-evm.mk
configs/platforms/am65xx-evm.mk
makerules/Makefile_linux

- Since the Platform name is different for am62a compared to other devices, introduce a new variable for am62axx-evm in configs/platforms/am62axx-evm.mk and refer to that variable when required.

makerules: Makefile_linux: Update the variable name for am62a

---

configs/platforms/am64xx-evm.mk

In continuation with the commit 2a2b29efe8818d44896fadeae7eca2b7fb8e8bec, in am64xx-evm.mk pass TI_DM as empty string since DM firmware is not applicable for am64x [0].
[0]: https://git.ti.com/cgit/arago-project/meta-ti/tree/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti.inc?h=scarthgap#n69

configs:platforms: Pass TI_DM as empty string for am64x

---

configs/platforms/am62dxx-evm.mk

Add a new makefile for am62dxx-evm, with the targets:
cryptodev
arm-benchmarks
u-boot
linux
linux-dtbs

configs: platforms: Add am62dxx-evm.mk toplevel makefile support for AM62D

---

configs/platforms/am62xxsip-evm.mk

For am62xxsip-evm, defconfigs are updated[1] to new u-boot machine variables. Hence update that in the top level makefile here.
While at it, Update the KERNEL_DEVICETREE_PREFIX expression to align with [1], ensuring that built DTBs are consistent and compatible with those produced by Yocto.
[1]: https://git.ti.com/cgit/arago-project/meta-ti/tree/meta-ti-bsp/conf/machine/am62xxsip-evm.conf?h=11.01.04

configs: platforms: Update uboot defconfigs and device tree prefixes

---

configs/platforms/am62lxx-evm.mk

Set TFA_SPD to opteed as newer silicon revision(1.1) of AM62L family boots with OP-TEE enabled[1].
[1]: https://git.ti.com/cgit/arago-project/meta-ti/commit/?h=11.01.11&id=0a02cd559a07af33a8111a1f5777b14862a52227

AM62L: platforms: Enable optee during TFA build
